### ISSUE TITLE
大佬出个下载智慧平台视频的工具

### ISSUE THREAD

**Issue by tingyue-wu** [Mystic-Stars/Textbook-Downloader#2]
大佬出个下载智慧平台视频的工具吧。以前可以idm下。现在idm无法下载了

**Comment by Mystic-Stars** [comment]
此程序暂时没有更新打算，但是有另外一位佬的程序也许能满足你的需要
https://github.com/52beijixing/smartedu-download

**Comment by tingyue-wu** [comment]
谢谢，这个果然可以，就是平台改版以后操作麻烦一点。
